### ISSUE TITLE
atosl: subprograms.c:141: dwarf_errmsg: DW_DLE_VERSION_STAMP_ERROR (48)

### ISSUE THREAD

**Issue by zhaodg** [facebook/atosl#14]
i use atosl like this,
atosl -o SomeApp.app.dSYM/Contents/Resources/DWARF/SomeApp --load-address 0x3c00 0x12345 0x55555
it's give me "atosl: subprograms.c:141: dwarf_errmsg: DW_DLE_VERSION_STAMP_ERROR (48)"
but i use -g ,
atosl -g -o SomeApp.app.dSYM/Contents/Resources/DWARF/SomeApp --load-address 0x3c00 0x12345 0x55555
it's give me "atosl: subprograms.c:235: dwarf_errmsg: DW_DLE_PUBNAMES_VERSION_ERROR"
how to fix it? i don't why?

**Comment by facebook-github-bot-0** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by zlandau** [comment]
I'm going to close this for now. I did notice that there have been a number of updates to libdwarf as well, so if you do run into it, try running the latest version from http://www.prevanders.net/dwarf.html.
