### ISSUE TITLE
fatal: unable to connect to git.code.sf.net:

### ISSUE THREAD

**Issue by deepoceanld** [facebook/atosl#24]
MBP:local ice$ brew install https://gist.github.com/zlandau/7550479/raw/f72753f6a59f6a3fadf9a2e2952a9f6846c15a8d/libdwarf.rb
######################################################################## 100.0%
==> Cloning git://git.code.sf.net/p/libdwarf/code
Cloning into '/Library/Caches/Homebrew/libdwarf--git'...
fatal: unable to connect to git.code.sf.net:
git.code.sf.net[0: 216.34.181.155]: errno=Operation timed out

Error: Failed to download resource "libdwarf"
Failure while executing: git clone --depth 1 --branch 20130729 git://git.code.sf.net/p/libdwarf/code /Library/Caches/Homebrew/libdwarf--git

**Comment by LegNeato** [comment]
Please reopen if this is still an issue
