### ISSUE TITLE
Add STABS support

### ISSUE THREAD

**Issue by zlandau** [facebook/atosl#31]
iOS binaries only store DWARF information in object files and dSYM binaries. The executables themselves use [STABS](https://sourceware.org/gdb/current/onlinedocs/stabs.html).

**Comment by facebook-github-bot-0** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by zlandau** [comment]
Merged, thanks @umanwizard
