### ISSUE TITLE
the link to libdwarf in the readme is 404

### ISSUE THREAD

**Issue by dinhviethoa** [facebook/atosl#34]
Here are some links that I found:

http://www.prevanders.net/dwarf.html
https://github.com/Distrotech/libdwarf

**Comment by zlandau** [comment]
Thanks for letting me know! I'll take a look at those, there are a few dwarf versions floating around so I have to make sure those ones work for atosl.

**Comment by zlandau** [comment]
Okay I took longer than I meant to before looking at this, but I just put up a fix. Thanks!

**Comment by dinhviethoa** [comment]
The link looks good to me.
