### ISSUE TITLE
Error message：atosl: atosl.c:985: dwarf_errmsg: DW_DLE_CU_ADDRESS_SIZE_BAD when run on linux os

### ISSUE THREAD

**Issue by fengxueren** [facebook/atosl#4]
My command is:
./atosl -A armv7 -o xx.app.dSYM/Contents/Resources/DWARF/xx  0x00555f95

it does not work on linux,the error message is:

atosl: atosl.c:985: dwarf_errmsg: DW_DLE_CU_ADDRESS_SIZE_BAD

But i can run atos command with osx ,the command is:
atos -arch armv7 -o xx.app.dSYM/Contents/Resources/DWARF/xx 0x00555f95

it show the corrert crash info.

**Comment by LegNeato** [comment]
Please reopen if this is still an issue
